### ISSUE TITLE
Force recalculation

### ISSUE THREAD

**Issue by flccrakers** [developerdizzle/react-virtual-list#23]
First of all, very nice work, I like your virtual-list, it's very usefull and super efficient.

I just has a suggestion: have a way to force the rendering of the list, even if we don't scroll.

I'm using your list to show a big list of complex components. On each of this component I have a check box (to be able to select it and make later an action). Outside of the virtual-list, I have "select-all" button. When I click on it my items array is updated and all the items are marked as checked, but the Virtualist is not updated, because I didn't scroll it yet.

Is there a way to improve this?
Thanks

**Comment by flccrakers** [comment]
Ok, sorry for this question, it's already implemented.

For those who asked themselves  the same question, you have to do this : 
```javascript
<VirtualList ref="list" ... />
```
```javascript
this.refs.list.forceUpdate();
```

**Comment by developerdizzle** [comment]
Hey @flccrakers, thanks for the kind words, and glad to hear you found a solution!  You might also find some useful stuff in the example implementation here https://github.com/developerdizzle/react-virtual-list/blob/gh-pages/App.jsx.  I didn't have to use `forceUpdate` there because I'm changing the component's properties.  Basically changing the state or props will make the component recalculate and update.
