### ISSUE TITLE
1,000,000 record can't render

### ISSUE THREAD

**Issue by hieugie** [developerdizzle/react-virtual-list#70]
i try filling 1,000,000 records and then i scroll down, its just can render about 400,000 records, do you thing that problem is because of padding-top is too big ?

**Comment by developerdizzle** [comment]
Hi @hieugie, thanks for the submission.  I believe this is because of browser-specific limitations.  Check out this post https://stackoverflow.com/a/10884837.  Basically each browser has a maximum page height, which can be reached with a large number of records.  Unfortunately it's not something I can fix in the scope of this project.
